#
#  Copyright 2022 Davide Bettio <davide@uninstall.it>
#
#  SPDX-License-Identifier: Apache-2.0 OR LGPL-2.1-or-later
#

name: Build and Test on Other Architectures

on: [push, pull_request]

env:
  otp_version: 21.0
  elixir_version: 1.9

jobs:
  build-and-test-other:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: ["armel", "armhf", "arm64"]

        include:
        - arch: "armel"
          distro: "wheezy"
          base_url: "http://archive.debian.org/debian"
          cflags: "-std=gnu99 -O2 -mthumb -mthumb-interwork -march=armv4t"

        - arch: "armhf"
          distro: "bullseye"
          base_url: "http://deb.debian.org/debian/"
          cflags: "-mcpu=cortex-a7 -mfloat-abi=hard -O2 -mthumb -mthumb-interwork"

        - arch: "arm64"
          distro: "buster"
          base_url: "http://deb.debian.org/debian/"
          cflags: "-O2"

        # It looks like we don't really support big-endian
        # - arch: "powerpc"
        #  distro: "jessie"
        #  base_url: "http://archive.debian.org/debian"
        #  cflags: "-std=gnu99 -Os"

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - uses: erlef/setup-beam@v1.10.0
      with:
        otp-version: ${{ env.otp_version }}
        elixir-version: ${{ env.elixir_version }}

    - name: apt update
      run: sudo apt update

    - name: Install required packages
      run: sudo apt install debootstrap gperf cmake

    - name: Set up QEMU
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - uses: actions/cache@v2
      id: cache
      with:
        path: debian-${{ matrix.arch }}.tar
        key: ${{ matrix.arch}}-${{ matrix.distro }}-${{ hashFiles('.github/workflows/build-and-test-other.yaml') }}

    - name: Bootrap Debian filesystem
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        sudo mkdir debian
        sudo debootstrap --no-check-gpg --arch ${{ matrix.arch }} \
          --include=file,gcc,g++,binutils,cmake,make,doxygen,gperf,zlib1g-dev,libssl-dev \
          ${{ matrix.distro }} debian ${{ matrix.base_url }}
        sudo tar -C debian -c . > debian-${{ matrix.arch }}.tar
        sudo rm -fr debian-${{ matrix.arch }}

    - name: Import docker container image
      run: |
        sudo docker import debian-${{ matrix.arch }}.tar debian-${{ matrix.arch }}

    - name: "Build: Tests"
      run: |
        mkdir build_tests
        cd build_tests
        cmake ..
        make erlang_test_modules
        make test_estdlib
        make test_eavmlib
        make test_alisp

    - name: "Build and Test: AtomVM on foreign arch"
      run: |
        docker run --rm -v $PWD:/atomvm -w /atomvm \
        -e CFLAGS="${{ matrix.cflags }}" -e CXXFLAGS="${{ matrix.cflags }}" \
        debian-${{ matrix.arch }} /bin/bash -c '
        file /bin/bash &&
        uname -a &&
        cc --version &&
        ld --version &&
        ldd --version &&
        echo $CFLAGS &&
        echo $CXXFLAGS &&
        cmake --version &&
        mkdir -p build &&
        cd build &&
        cmake .. &&
        cp ../build_tests/tests/erlang_tests/*.beam tests/erlang_tests/ &&
        cp ../build_tests/tests/libs/estdlib/*.avm tests/libs/estdlib/  &&
        cp ../build_tests/tests/libs/eavmlib/*.avm tests/libs/eavmlib/ &&
        cp ../build_tests/tests/libs/alisp/*.avm tests/libs/alisp/ &&
        make AtomVM &&
        make test-erlang &&
        file ./tests/test-erlang &&
        ./tests/test-erlang &&
        file ./src/AtomVM &&
        ./src/AtomVM tests/libs/estdlib/test_estdlib.avm &&
        ./src/AtomVM tests/libs/eavmlib/test_eavmlib.avm &&
        ./src/AtomVM tests/libs/alisp/test_alisp.avm
        '
