#
#  Copyright 2022 Paul Guyot <pguyot@kallisys.net>
#
#  SPDX-License-Identifier: Apache-2.0 OR LGPL-2.1-or-later
#

name: Run tests with BEAM

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ["21", "22", "23"]

    steps:
    # Setup
    - name: "Checkout repo"
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp }}

    - name: "APT update"
      run: sudo apt update -y

    - name: "Install deps"
      run: sudo apt install -y cmake gperf zlib1g-dev ninja-build

    # Build
    - name: "Build: create build dir"
      run: mkdir build

    - uses: actions/cache@v2
      id: cache
      with:
        path: 'build/tests/**/*.beam'
        key: ${{ matrix.otp }}-${{ hashFiles('**/run-tests-with-beam.yaml', 'tests/**/*.erl') }}

    - name: "Build: run cmake"
      working-directory: build
      run: |
        cmake -G Ninja ..
        # git clone will use more recent timestamps than cached beam files
        # touch them so we can benefit from the cache and avoid costly beam file rebuild.
        find . -name '*.beam' -exec touch {} \;

    - name: "Build: run ninja"
      working-directory: build
      run: ninja

    # Test
    - name: "Test: test-erlang with BEAM"
      timeout-minutes: 10
      working-directory: build
      run: |
        ./tests/test-erlang -b
